apiVersion: v1
kind: Secret
metadata:
  name: puissance4-secrets
  namespace: puissance4
type: Opaque
stringData:
  database-url: jdbc:postgresql://postgres-service:5432/puissance4
  database-username: postgres
  database-password: postgres
  jwt-secret: puissance4-secret-key-very-long-for-security-256bits
  jwt-expiration: "86400000"
